const { EmailClient } = require("@azure/communication-email");
const { generateProposalPDF } = require("./pdf.service");

function createEmailClient() {
  const connectionString = process.env.ACS_EMAIL_CONNECTION_STRING;

  if (!connectionString) {
    throw new Error("ACS_EMAIL_CONNECTION_STRING is not configured");
  }

  return new EmailClient(connectionString);
}

function buildEmailContent({ companyName, savedAs }) {
  const plainText = `
Dear Recipient,

Please find the attached RFP proposal document.

${companyName ? `Company: ${companyName}\n` : ""}${savedAs ? `Reference: ${savedAs}\n` : ""}

This proposal was generated by the AI RFP Proposal Generator and is attached as a PDF document for your review.

Best regards,
POD 5 Team
Saritha, Davinder, Prasanna, Muthu & Jovitto
  `.trim();

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background: linear-gradient(135deg, #f7f0e8 0%, #f1e7db 100%); border-radius: 16px;">
      <div style="background: linear-gradient(120deg, rgba(255, 95, 31, 0.96) 0%, rgba(208, 74, 2, 0.96) 100%); padding: 30px; border-radius: 12px; margin-bottom: 20px;">
        <h2 style="color: white; margin: 0; font-size: 28px;">🤖 AI RFP Proposal Generator</h2>
        <p style="color: rgba(255, 255, 255, 0.9); margin: 10px 0 0 0; font-size: 14px;">Powered by POD 5 Team</p>
      </div>
      
      <div style="background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
        <p style="font-size: 16px; color: #2d2d2d; margin-bottom: 20px;">Dear Recipient,</p>
        
        <p style="font-size: 15px; color: #2d2d2d; line-height: 1.6;">
          Please find the attached <strong>RFP Proposal document</strong> generated specifically for your requirements.
        </p>
        
        ${companyName ? `
        <div style="background: #fff7ef; padding: 15px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #ff5f1f;">
          <p style="margin: 0; color: #2d2d2d;"><strong>Company:</strong> ${companyName}</p>
        </div>
        ` : ""}
        
        ${savedAs ? `
        <div style="background: #f8fafc; padding: 15px; border-radius: 8px; margin: 20px 0;">
          <p style="margin: 0; color: #64748b; font-size: 14px;"><strong>Reference:</strong> ${savedAs}</p>
        </div>
        ` : ""}
        
        <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; margin: 20px 0; border: 1px solid #86efac;">
          <p style="margin: 0; color: #166534; font-size: 15px;">
            📎 <strong>Attachment:</strong> Your proposal is attached as a professionally formatted PDF document.
          </p>
        </div>
        
        <p style="font-size: 15px; color: #2d2d2d; line-height: 1.6; margin-top: 20px;">
          This proposal has been carefully crafted using AI-powered analysis of your RFP requirements,
          incorporating industry best practices and relevant past proposal insights.
        </p>
        
        <hr style="border: none; border-top: 2px solid #e2e8f0; margin: 30px 0;">
        
        <p style="color: #64748b; font-size: 14px; margin-bottom: 5px;">
          Best regards,
        </p>
        <p style="color: #2d2d2d; font-size: 15px; font-weight: bold; margin: 5px 0;">
          POD 5 Team
        </p>
        <p style="color: #64748b; font-size: 13px; font-style: italic; margin: 5px 0;">
          Saritha • Davinder • Prasanna • Muthu • Jovitto
        </p>
      </div>
      
      <div style="text-align: center; margin-top: 20px; padding: 15px;">
        <p style="color: #64748b; font-size: 12px; margin: 0;">
          © 2026 AI RFP Proposal Generator • Powered by Azure AI
        </p>
      </div>
    </div>
  `.trim();

  return { plainText, html };
}

/**
 * Send email with proposal as PDF attachment using Azure Communication Services Email
 * @param {Object} options - Email options
 * @param {string} options.to - Recipient email
 * @param {string} options.subject - Email subject
 * @param {string} options.proposalText - Proposal content
 * @param {string} options.companyName - Company name (optional)
 * @param {string} options.savedAs - Blob name (optional)
 * @param {Object} options.rfpData - RFP metadata (optional)
 * @param {Object} options.requirementsJson - Requirements data (optional)
 */
async function sendProposalEmail({ to, subject, proposalText, companyName, savedAs, rfpData, requirementsJson }) {
  const client = createEmailClient();

  const fromEmail = process.env.ACS_EMAIL_FROM;
  const fromName = process.env.ACS_EMAIL_FROM_NAME || "AI RFP Proposal Generator";

  if (!fromEmail) {
    throw new Error("ACS_EMAIL_FROM is not configured");
  }

  // Generate PDF from proposal
  const pdfBuffer = await generateProposalPDF({
    proposal: proposalText,
    companyName,
    rfpData,
    requirementsJson,
    savedAs
  });

  // Build email content
  const { plainText, html } = buildEmailContent({
    companyName,
    savedAs
  });

  // Generate filename for PDF attachment
  const pdfFilename = savedAs
    ? savedAs.replace('.txt', '.pdf')
    : `proposal-${Date.now()}.pdf`;

  const message = {
    senderAddress: fromEmail,
    recipients: {
      to: [{ address: to }]
    },
    content: {
      subject,
      plainText,
      html
    },
    attachments: [
      {
        name: pdfFilename,
        contentType: "application/pdf",
        contentInBase64: pdfBuffer.toString('base64')
      }
    ],
    senderDisplayName: fromName
  };

  try {
    const poller = await client.beginSend(message);
    const result = await poller.pollUntilDone();

    if (!result) {
      throw new Error("Azure Communication Services Email returned an empty result");
    }

    if (result.status && result.status.toLowerCase() !== "succeeded") {
      throw new Error(`Email send failed with status: ${result.status}`);
    }

    return {
      success: true,
      messageId: result.id,
      message: "Email sent successfully with PDF attachment",
      attachmentName: pdfFilename
    };
  } catch (error) {
    console.error("Azure email sending error:", error);
    throw new Error(`Failed to send email: ${error.message}`);
  }
}

module.exports = {
  sendProposalEmail
};

// Made with Bob
