const { EmailClient } = require("@azure/communication-email");

function createEmailClient() {
  const connectionString = process.env.ACS_EMAIL_CONNECTION_STRING;

  if (!connectionString) {
    throw new Error("ACS_EMAIL_CONNECTION_STRING is not configured");
  }

  return new EmailClient(connectionString);
}

function buildEmailContent({ proposalText, companyName, savedAs }) {
  const plainText = `
Dear Recipient,

Please find the generated RFP proposal below:

${companyName ? `Company: ${companyName}\n` : ""}${savedAs ? `Reference: ${savedAs}\n` : ""}
---

${proposalText}

---

This proposal was generated by the AI RFP Proposal Generator.

Best regards,
POD 5 Team
  `.trim();

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
      <h2 style="color: #6366f1;">RFP Proposal</h2>
      <p>Dear Recipient,</p>
      <p>Please find the generated RFP proposal below:</p>
      ${companyName ? `<p><strong>Company:</strong> ${companyName}</p>` : ""}
      ${savedAs ? `<p><strong>Reference:</strong> ${savedAs}</p>` : ""}
      <hr style="border: 1px solid #e2e8f0; margin: 20px 0;">
      <div style="background: #f8fafc; padding: 20px; border-radius: 8px; white-space: pre-wrap; font-family: monospace; font-size: 14px;">
${proposalText}
      </div>
      <hr style="border: 1px solid #e2e8f0; margin: 20px 0;">
      <p style="color: #64748b; font-size: 14px;">
        This proposal was generated by the AI RFP Proposal Generator.
      </p>
      <p style="color: #64748b; font-size: 14px;">
        Best regards,<br>
        <strong>POD 5 Team</strong><br>
        <em>Saritha, Davinder, Prasanna, Muthu & Jovitto</em>
      </p>
    </div>
  `.trim();

  return { plainText, html };
}

/**
 * Send email with proposal using Azure Communication Services Email
 * @param {Object} options - Email options
 * @param {string} options.to - Recipient email
 * @param {string} options.subject - Email subject
 * @param {string} options.proposalText - Proposal content
 * @param {string} options.companyName - Company name (optional)
 * @param {string} options.savedAs - Blob name (optional)
 */
async function sendProposalEmail({ to, subject, proposalText, companyName, savedAs }) {
  const client = createEmailClient();

  const fromEmail = process.env.ACS_EMAIL_FROM;
  const fromName = process.env.ACS_EMAIL_FROM_NAME || "AI RFP Proposal Generator";

  if (!fromEmail) {
    throw new Error("ACS_EMAIL_FROM is not configured");
  }

  const { plainText, html } = buildEmailContent({
    proposalText,
    companyName,
    savedAs
  });

  const message = {
    senderAddress: fromEmail,
    recipients: {
      to: [{ address: to }]
    },
    content: {
      subject,
      plainText,
      html
    },
    senderDisplayName: fromName
  };

  try {
    const poller = await client.beginSend(message);
    const result = await poller.pollUntilDone();

    if (!result) {
      throw new Error("Azure Communication Services Email returned an empty result");
    }

    if (result.status && result.status.toLowerCase() !== "succeeded") {
      throw new Error(`Email send failed with status: ${result.status}`);
    }

    return {
      success: true,
      messageId: result.id,
      message: "Email sent successfully"
    };
  } catch (error) {
    console.error("Azure email sending error:", error);
    throw new Error(`Failed to send email: ${error.message}`);
  }
}

module.exports = {
  sendProposalEmail
};

// Made with Bob
