require("dotenv").config();

module.exports = {
  PORT: process.env.PORT || 3000,

  AZURE_STORAGE_CONNECTION_STRING: process.env.AZURE_STORAGE_CONNECTION_STRING,
  BLOB_CONTAINER_INCOMING: process.env.BLOB_CONTAINER_INCOMING,
  BLOB_CONTAINER_OUTPUT: process.env.BLOB_CONTAINER_OUTPUT,
  BLOB_CONTAINER_PAST: process.env.BLOB_CONTAINER_PAST,

  AZURE_SEARCH_ENDPOINT: process.env.AZURE_SEARCH_ENDPOINT,
  AZURE_SEARCH_API_KEY: process.env.AZURE_SEARCH_API_KEY,
  AZURE_SEARCH_INDEX_NAME: process.env.AZURE_SEARCH_INDEX_NAME,

  AZURE_OPENAI_ENDPOINT: process.env.AZURE_OPENAI_ENDPOINT,
  AZURE_OPENAI_API_KEY: process.env.AZURE_OPENAI_API_KEY,
  AZURE_OPENAI_DEPLOYMENT: process.env.AZURE_OPENAI_DEPLOYMENT,
  AZURE_OPENAI_EMBEDDING_DEPLOYMENT: process.env.AZURE_OPENAI_EMBEDDING_DEPLOYMENT,
  AZURE_OPENAI_API_VERSION: process.env.AZURE_OPENAI_API_VERSION,

  BING_SEARCH_SUBSCRIPTION_KEY: process.env.BING_SEARCH_SUBSCRIPTION_KEY,
  BING_SEARCH_ENDPOINT: process.env.BING_SEARCH_ENDPOINT || "https://api.bing.microsoft.com/v7.0/search"
};